TravellersCom/config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :users, path: "", path_names: { sign_in: "login", sign_out: "logout", 
    sign_up: "register" }
    root to: 'pages#home'

  resources :users
    
  resources :devise do
    resources :user_relationships, only: [:create]
  end

  resources :user_relationships, only: [:destroy]

  resources :trip_details do 
    resources :reviews
  end

  get "admin/dashboard" => "admin/dashboard#index"
  get "/home" => "pages#home"
  get "/search" => "trip_details#search"

  # Routes for nav items.
  get "user/profile" => "pages#profile"

  #Routes for tabs.
  get "user/followers" => "user_relationships#_followers"
  get "user/following" => "user_relationships#_following"
    
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

TravellersCom/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_trip_detail
  before_action :find_review, only: [:edit, :update, :destroy]

  # This class defines CRUD Operations for handling user reviews on trip details.
  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.trip_detail_id = @trip_detail.id
    @review.user_id = current_user.id
    if @review.save
      redirect_to trip_detail_path(@trip_detail)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @review.update(review_params)
      redirect_to trip_detail_path(@trip_detail)
    else
      render 'edit'
    end
  end

  def destroy
    @review.destroy
    redirect_to trip_detail_path(@trip_detail)
  end

  private
    def review_params
      params.require(:review).permit(:rating, :review)
    end

    def find_trip_detail
      @trip_detail = TripDetail.find(params[:trip_detail_id])
    end

    def find_review
      @review = Review.find(params[:id])
    end

end

TravellersCom/app/helpers/reviews_helper.rb
module ReviewsHelper
end

TravellersCom/app/views/reviews/_form.html.erb
<%= form_for([@trip_detail, @trip_detail.reviews.build]) do |f| %>
  <div class="row">
    <div class="col-1">
      <%= f.label :rating %>
    </div>
    <div class="col-11">
      <div id="rating-form">
        <%= f.number_field :rating, max: 5 %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-1">
      <%= f.label :review %>
    </div>
    <div class="col-11">
        <%= f.text_area :review, rows: 5 %>
    </div>
  </div>
  <div class="row">
     <div class="col-12" style = "text-align: center;">
      <%= f.submit 'Create Review', class: "btn btn-dark" %>
    </div>
  </div>  
<% end %>

 <%# Scripts for displaying star ratings. %>
<script>
  $('#rating-form').raty({
    path: '/assets/images',
    scoreName: 'review[rating]'
  });
</script>

TravellersCom/app/views/reviews/_review.html.erb
<div class="reviews-show">
  <div class="row">
    <div class="col-11">
      <p>
        <% @trip_review = Review.find_by(:trip_detail_id => @trip_detail.id) %>
        <%= image_tag @trip_review.user.avatar, class: "rounded-circle",
        style: "width: 30px; height: 30px;" %>
        <strong><%= link_to @trip_review.user.full_name, user_path(@trip_review.user) %></strong>
      </p>
      <p>
        <div class="review-rating" data-score="<%= review.rating %>"></div>
        <%= review.rating%>
        <%= review.review %>
      </p>
    </div>
    <div class="col-1">
    <% if user_signed_in? %>
      <% if review.user_id == current_user.id %>
        <div class="dropdown">
          <button type="button" class="dropdown-btn btn-outline dropdown-toggle dropdown-toggle-split" 
          data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="sr-only">Toggle Dropdown</span>
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item">
              <%= link_to 'Edit', edit_trip_detail_review_path(review.trip_detail, review) %>
            </a>
            <a class="dropdown-item">
              <%= link_to 'Delete', trip_detail_review_path(review.trip_detail, review), 
              method: :delete, data: { confirm: "Delete review?" } %>
            </a>
          </div>
        </div>
      <% end %>
    <% end %>
    </div>
  </div>
</div>

TravellersCom/app/views/reviews/edit.html.erb
<div style = "margin:auto; text-align:center; padding-top: 30px; padding-bottom: 30px; height: 100vh;">
  <h5> Edit Review <hr></h5>
  <%= simple_form_for([@trip_detail, @review]) do |f| %>
  <div style = "max-width: 500px; margin:auto; ">
    <div class = "row">
      <div class = "col" style = "text-align:right; max-width: 80px;">
        <%= f.label :rating %>
      </div>
      <div class = "col">
        <%= f.number_field :rating, class: "form-control" %>
      </div>
    </div>
    <div class = "row">
      <div class = "col" style = "text-align:right; max-width: 80px;">
        <%= f.label :review %>
      </div>
      <div class = "col">
        <%= f.text_area :review, class: "form-control", rows:8 %>
      </div>
    </div>
    <div class = "row">
      <div class = "col">
        <%= f.submit %>
      </div>
    </div>
  </div>
<% end %>
</div>

TravellersCom/app/views/reviews/new.html.erb
<h2>Leave Review</h2>
<%= render 'form' %>