TravellersCom/config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :users, path: "", path_names: { sign_in: "login", sign_out: "logout", 
    sign_up: "register" }
    root to: 'pages#home'

  resources :users
    
  resources :devise do
    resources :user_relationships, only: [:create]
  end

  resources :user_relationships, only: [:destroy]

  resources :trip_details do 
    resources :reviews
  end

  get "admin/dashboard" => "admin/dashboard#index"
  get "/home" => "pages#home"
  get "/search" => "trip_details#search"

  # Routes for nav items.
  get "user/profile" => "pages#profile"

  #Routes for tabs.
  get "user/followers" => "user_relationships#_followers"
  get "user/following" => "user_relationships#_following"
    
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

TravellersCom/app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

TravellersCom/app/views/layouts/_navbar.html.erb
<nav class = "navbar navbar-dark bg-dark container-fluid">
  <%= link_to 'Travellers Co', root_path, class: 'navbar-brand col-sm-1' %>
  <% if user_signed_in? %>
    <%= form_tag search_path, :method => 'get', class: "form-inline" do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search Trips", 
      class: "form-control mr-sm-2 mobile-search" %>
      <%= submit_tag "Search", class: "btn btn-outline-light my-2 my-sm-0 btn-search" %>
    <% end %>
    <button class = "navbar-toggler" type = "button" data-toggle = "collapse" 
    data-target = "#navbarNavAltMarkup" aria-controls = "navbarNavAltMarkup" aria-expanded = "false" 
    aria-label = "Toggle navigation">
      <%= image_tag user_avatar(current_user), class: "rounded-circle nav-avatar"%>
      <div class="h6 d-inline-block nav-name">
        <%= current_user.full_name %>
      </div>
      <svg xmlns = "http://www.w3.org/2000/svg" width = "16" height = "16" fill = "currentColor" 
      class = "bi bi-chevron-double-down" viewBox = "0 0 16 16">
        <path fill-rule = "evenodd" d = "M1.646 6.646a.5.5 0 0 1 .708 0L8 12.293l5.646-5.647a.5.5
        0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/>
        <path fill-rule = "evenodd" d = "M1.646 2.646a.5.5 0 0 1 .708 0L8 8.293l5.646-5.647a.5.5 
        0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/>
      </svg>
    </button>
    <div class = "collapse navbar-collapse ml-auto overlay navbar-items" id = "navbarNavAltMarkup" >
      <div class = "navbar-nav">
        <ul class = "nav-item">
          <%= link_to 'My Trips', trip_details_path, class: "nav-item" %>
        </ul>
        <ul class = "nav-item">
          <%= link_to 'My Profile', edit_user_registration_path, class: "nav-item" %>
        </ul>
        <ul class = "nav-item">
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "nav-item" %>
        </ul>
      </div>
    </div>
  <% end %>
</nav>

TravellersCom/app/views/layouts/_tabs.html.erb
<%= tabs_tag do |tab| %>
  <ul class="nav nav-tabs " role="tablist">
    <li class="nav-item" role="tab">
    <%= tab.profile 'Profile', edit_user_registration_path, :class => 'nav-link active'  %>
    </li>
    <li class="nav-item" role="tab">
    <%= tab.followers 'Followers', user_followers_path, :class => 'nav-link active'  %>
    </li>
    <li class="nav-item" role="tab">
    <%= tab.following 'Following', user_following_path, :class => 'nav-link active'  %>
    </li>
  </ul>
<% end %>

TravellersCom/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Traveller's Community</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': true %>
  </head>
  <body>
    <div class="wrapper">
      <div style = "width: 100%; ">
        <%= render 'layouts/navbar' %>
      </div>
      <%= yield %>
    </div>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBH2rc3FNR9g5IJZplnqvfEGjOKIcj1ED8&libraries=places&callback=initMap"
    async defer data-turbolinks-eval="false" type="text/javascript"></script>
  </body>
</html>