TravellersCom/config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :users, path: "", path_names: { sign_in: "login", sign_out: "logout", 
    sign_up: "register" }
    root to: 'pages#home'

  resources :users
    
  resources :devise do
    resources :user_relationships, only: [:create]
  end

  resources :user_relationships, only: [:destroy]

  resources :trip_details do 
    resources :reviews
  end

  get "admin/dashboard" => "admin/dashboard#index"
  get "/home" => "pages#home"
  get "/search" => "trip_details#search"

  # Routes for nav items.
  get "user/profile" => "pages#profile"

  #Routes for tabs.
  get "user/followers" => "user_relationships#_followers"
  get "user/following" => "user_relationships#_following"
    
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

TravellersCom/app/models/trip_detail.rb
class TripDetail < ApplicationRecord
  belongs_to :user
  has_many :reviews,  :dependent => :destroy
  has_many_attached :photos,  :dependent => :destroy

  #  Nav-bar search
  def self.search(search)
    if search
      where(["location ILIKE ?", "%#{search}%"])
    else
      all
    end
  end

end

TravellersCom/app/controllers/trip_details_controller.rb
class TripDetailsController < InheritedResources::Base
  before_action :authenticate_user!
  actions :index, :show, :new, :create, :destroy

  # CRUD Operations for trip details.
  def index
    @trip_detail = TripDetail.new
    super
  end

  def show
    @trip_detail = TripDetail.find(params[:id])
    add_breadcrumb("#{@trip_detail.user.full_name} - #{@trip_detail.location}")
    @review = Review.new
    if @trip_detail.reviews.blank?
      @avg_review = 0
    else
      @avg_review = @trip_detail.reviews.average(:rating).round(2)
    end 
  end

  # Queries for search and filters.
  def search
    if !params[:search].blank?
      @trip_detail = TripDetail.search(params[:search])
    end
    if !params[:keywords].blank?
      @trip_detail = TripDetail.search(params[:keywords])
      @trip_detail = @trip_detail.where(["trip_details.start = ?", params[:start_date]]) if params[:start_date].present?
      @trip_detail = @trip_detail.where(["trip_details.end = ?", params[:end_date]]) if params[:end_date].present?
      if params[:gender].present?
        if params[:gender] == "Male" || params[:gender] == "Female"
          if params[:gender] == "Male"
            @trip_detail = @trip_detail.joins(:user).where(users: {gender: 1})
          else
            @trip_detail = @trip_detail.joins(:user).where(users: {gender: 2})
          end
        end
      end
    else
      @trip_detail = TripDetail.search(params[:search])
    end
  end

  private
    def trip_detail_params
      params.require(:trip_detail).permit(:location, :start, :end, :description, :photos => []).
      merge(:user_id => current_user.id)
    end

    def filter_params
      params.permit(:keywords, :start_date, :end_date, :gender)
    end

end

TravellersCom/app/helpers/trip_details_helper.rb
module TripDetailsHelper
end

TravellersCom/app/views/trip_details/_form.html.erb
<%= form_with(model: trip_detail, local: true, data: {controller: "places", 
action: "google-maps-callback@window->places#initMap" }) do |form| %>
  <% if trip_detail.present? %>
    <% if trip_detail.errors.any? %>
      <div id="error_explanation">
        <h2>
        <%= pluralize(trip_detail.errors.count, "error") %> prohibited this trip_detail from being saved:
        </h2>        
        <ul>
          <% trip_detail.errors.full_messages.each do |message| %>
            <li><%= message%></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  <% end %>
  <div class="row">
    <div class="col-12">
      <%= form.text_field :location, placeholder: "Add your Location",
      class: "form-control", data: { target: "places.field" } %>
    </div>
  </div>
  <div class="row">
    <div class="col-6">
      <%= form.date_field :start, placeholder: "Date From", class: "form-control" %>
    </div>
    <div class="col-6">
      <%= form.date_field :end, placeholder: "Date To", class: "form-control" %>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <%= form.text_area :description, placeholder: "Add your Trip Description",
      class: "form-control", rows: "8", cols: "25" %>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <%= form.file_field :photos, multiple: true, accept:'image/*' %>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      </br>
      <%= form.submit 'Create Trip Detail', class: "btn btn-dark" %> 
    </div>
  </div>
<% end %>

TravellersCom/app/views/trip_details/edit.html.erb
<h1>Editing Trip Detail</h1>
<%= render 'form', trip_detail: @trip_detail %>
<%= link_to 'Show', @trip_detail %> |
<%= link_to 'Back', trip_details_path %>

TravellersCom/app/views/trip_details/index.html.erb
<section class = "container-fluid signed-in-content">
  <div class = "row">
    <div class = "col-6">
      <h3>My Trips</h3>
    </div>
    <div class = "col-6 display-none">
    <%= link_to(trip_details_path) do %>
      <button class = "btn btn-dark">Add New Trip</button>
      <hr>
    <% end %>
    </div>
  </div>
  <div class = "row">
    <div class = "col-lg-6 col-md-6 col-sm-12">
      <div class = "row">
        <div class = "col-12">
          <% @trip_details.each do |trip_detail| %>
            <% if trip_detail.user_id == current_user.id %>
              <%= link_to(trip_detail) do %>
                <div>
                  <%= trip_detail.location %> </br>
                  <%= trip_detail.start %> - <%= trip_detail.end %> 
                  <hr>
                </div>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <div class = "col-6 display-none">
      <%= render 'form', trip_detail: @trip_detail %>
    </div>
  </div>
  <div class = "row display-lg-none">
    <div class = "col-12 display-lg-none">
      <%= link_to(trip_details_path) do %>
        <button class = "btn btn-dark">Add New Trip</button>
        <hr>
      <% end %>
    </div>
  </div>
  <div class = "row display-lg-none">
    <div class = "col-12 col-sm-12 display-lg-none">
      <%= render 'form', trip_detail: @trip_detail, class:"display-lg-none" %>
    </div>
  </div>
</section>

TravellersCom/app/views/trip_details/new.html.erb
<h1>New Trip Detail</h1>
<%= render 'form', trip_detail: @trip_detail %>
<%= link_to 'Back', trip_details_path %>

TravellersCom/app/views/trip_details/search.html.erb
<section class = "container-fluid signed-in-content">
  <div class = "search-heading">
  <h2>Search Results </h2>
  <hr>
  </div>
  <div class = "row filter-row">
    <%= form_tag search_path, :method => 'get', class: "form-inline" do %>
      <div class = "col">
        Keywords:
        <%= text_field_tag :keywords %>
      </div>
      <div class = "col">
        Start Date:
        <%= date_field_tag :start_date, class: 'form-control' %>
      </div>
      <div class = "col">
        End Date:
        <%= date_field_tag :end_date, class: 'form-control' %>
      </div>
      <div class = "col">
        Gender:<br>
        <%= select_tag :gender, options_for_select(['Male', 'Female']), 
        class: 'form-control', include_blank: "--" %>
      </div>
      <div class = "col">
        <%= submit_tag "Go", class: "btn btn-dark filter-btn" %>
      </div>
    <% end %>
  </div>
  <hr>
  <div class = "row">
    <div class = "col-9">
      <% @trip_detail.each do |trip| %>
        <%= link_to(trip) do %>
          <h6>
            <strong><%= trip.location %></strong>
          </h6>
          <i><%= trip.start %> - <%= trip.end %></i></br>
        <% end %></br>
        <%= image_tag (trip.user.avatar), class: "rounded-circle", style: "width: 25px; height: 25px;" %>
        <%= link_to trip.user.full_name, user_path(trip.user) %>
        <hr>
      <% end %>
    </div>
  </div>
</section>

TravellersCom/app/views/trip_details/show.html.erb
<section class = "container-fluid signed-in-content">
  <div class = "row">
    <div class = "col-12">
      <p id = "notice" style = "text-align:center;"><%= notice %></p>
    </div>
  </div>
  <div class = "row">
    <div class = "col-12">
      <%= render 'shared/breadcrumbs' %>
    </div>
  </div>
  <div class = "row">
    <div class = "col-1" style = "max-width: 60px;">
      <%= image_tag user_avatar(@trip_detail.user), class: "rounded-circle d-inline-block",
        style: "width: 50px; height: 50px;" %>
    </div>
    <div class = "col-11">
        <h5><%= @trip_detail.user.full_name %></h5>
        <h6><%= @trip_detail.created_at.strftime("%b %d, %Y") %></h6>
    </div>
  </div>
  <div class = "row">
    <div class = "col-12">
      <h3><%= @trip_detail.location %></h3>
    </div>
      <div id = "average-review-rating" data-score = <%= @average_review %>></div>
  </div>
  <div class = "row" style = "margin: auto;">
    <div class = "col-12" style = "background-color:whitesmoke; padding: 10px;">
      <center>
      <% if @trip_detail.photos.attached? %>
        <% (0...@trip_detail.photos.count).each do |photo| %>
          <div class = "card-trip-img d-inline-block" style = "">
            <%= image_tag (@trip_detail.photos[photo]), 
            class:"trip-img" %>
          </div>
        <% end %>
      <% else %>
        <p style = "text-align:center">No Photos Attached</p>
      <% end %>
      </center>
    </div>
  </div>
  <div class = "row description-show">
    <div class = "col-12">
      <%= @trip_detail.description %>
    </div>
  </div>
  <div class = "write-review">
    <div class = "row">
      <div class = "col-12">
        <h5>Leave a Review</h5>
      </div>
      <div class = "col-12">
        <%= render 'reviews/form' %>
      </div>
    </div>
  </div>
  <div class = "row">
    <div class = "col-12">
      <% if @trip_detail.reviews.count > 0 %>
        <%# <%= render @trip_detail.reviews %> 
        <%= render @trip_detail.reviews %>
      <% end %>
    </div>
  </div>
</section>

 <%# Scripts for displaying star ratings. %>
<script>
  $('.review-rating').raty({
    readOnly: true,
    size: 36,
    score: function() {
      return $(this).attr('data-score');
    },
    path: '/assets/images'
  });
</script>

<script>
  $('.average-review-rating').raty({
    readOnly: true,
    path: '/assets/images',
    score: function () {
      return $(this).attr('data-score')
    }
  });
</script>